dtb-$(CONFIG_ARCH_RTD129x) += rtd-1295-fpga.dtb
dtb-$(CONFIG_ARCH_RTD129x) += rtd-1295-giraffe.dtb
dtb-$(CONFIG_ARCH_RTD129x) += rtd-1295-giraffe-1GB.dtb
dtb-$(CONFIG_ARCH_RTD129x) += rtd-1295-giraffe-dongle.dtb
dtb-$(CONFIG_ARCH_RTD129x) += rtd-1295-giraffe-1GB.CMAx2.dtb
dtb-$(CONFIG_ARCH_RTD129x) += rtd-1295-giraffe-1.5GB.dtb
dtb-$(CONFIG_ARCH_RTD129x) += rtd-1295-giraffe-2GB.dtb
dtb-$(CONFIG_ARCH_RTD129x) += rtd-1295-giraffe-2GB-tee.dtb
dtb-$(CONFIG_ARCH_RTD129x) += rtd-1295-qa-rescue.dtb
dtb-$(CONFIG_ARCH_RTD129x) += rtd-1295-xen-giraffe.dtb
dtb-$(CONFIG_ARCH_RTD129x) += rtd-1294-giraffe-1GB.dtb
dtb-$(CONFIG_ARCH_RTD129x) += rtd-1296-qa-rescue.dtb
dtb-$(CONFIG_ARCH_RTD129x) += rtd-1295-recovery.dtb 
dtb-$(CONFIG_ARCH_RTD129x) += rtd-1296-saola-2GB.dtb
dtb-$(CONFIG_ARCH_RTD129x) += rtd-1296-saola-2GB-tee.dtb


always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
