
ccflags-y += -I$(srctree)/drivers/media/platform/rtk_hdmirx/reg_include
ccflags-y += -I$(srctree)/drivers/media/platform/rtk_hdmirx/

obj-$(CONFIG_RTK_HDMIRX)    += hdmiHdmi.o hdmiEDID.o hdmiPhy.o hdmiMS.o
